Feat/overlapping timespan check
caas-team/GoKubeDownscaler pull request #36
Opened 2024-09-06 08:43 UTC by jon4skl

## Motivation

needed to open a new pull request 

## Changes

## Tests done

## TODO

- [x] I've assigned myself to this PR

2024-09-11 07:19 UTC, jonathan-mayer commented
Resolved the Merge conflicts. Before we merge we should wait on a review from @JTaeuber

2024-09-12 12:18 UTC, JTaeuber requested changes

2024-09-12 12:18 UTC, JTaeuber commented on internal/pkg/values/util.go
> +	if weekday == 0 {
Remove if

2024-09-12 12:18 UTC, JTaeuber commented on internal/pkg/values/util.go
> +	if weekday == 6 {
Remove if

2024-09-12 12:27 UTC, JTaeuber approved these changes

2024-09-13 06:22 UTC, jonathan-mayer approved these changes

2024-09-13 08:05 UTC, JTaeuber requested changes
Check doesn't work yet.

2024-09-13 08:39 UTC, JTaeuber requested changes

2024-09-13 08:39 UTC, JTaeuber commented on internal/pkg/values/timespan.go
> +	sameWeedays := relativeTimeSpan{
```suggestion
sameWeekdays := relativeTimeSpan{
```

2024-09-13 09:59 UTC, jonathan-mayer commented
There is a pretty big problem with the current implementation. 
![image](https://github.com/user-attachments/assets/e4a0fb8e-7e92-4a61-8834-4e298075fc2d)
This has to be resolved first. I dont think this will be resolved any time soon though,  i will push a test for this and we should let this feature wait for a bit

2025-01-02 13:24 UTC, jonathan-mayer commented
closing this until i can work on this

2025-01-02 13:24 UTC, closed without merging