Feat/add content to site
caas-team/GoKubeDownscaler pull request #69
Opened 2024-11-05 08:06 UTC by jonathan-mayer

## Motivation

Solves #63
Related to #38 

## Changes

## Tests done

- [X] tested website locally

## TODO

2025-02-13 09:13 UTC, JTaeuber commented on website/src/components/CaasAvatar.tsx
> +  const description = "The container as a service team at Deutsch Telekom IT";
```suggestion
  const description = "The container as a service team at Deutsche Telekom IT";
```

I know our name is CaaS@DTIT but it might be a consideration to write from the Deutsche Telekom IT. 🤷‍♂️

2025-02-13 09:49 UTC, jonathan-mayer commented on website/content/docs/0 - downscaler/0 - Arguments.mdx
> +  :::info
Idk, the line between what counts as an `ìnfo` and what as a `note` is pretty thin. But I do think this one is an info more than it is a note. 
This only explains what explicit include does. There is nothing to "note" its just an information on its function.

2025-02-13 10:01 UTC, jonathan-mayer commented on website/content/docs/0 - downscaler/0 - Arguments.mdx
> +The runtime configuration set by the cli arguments will be overwritten by their [respective environment variables](ref:docs-environment-variables#runtime-coniguration) if they are both set argument.
It was wrong although not because of layers, since runtime configuration is handled separately.

2025-02-13 10:18 UTC, JTaeuber requested changes

2025-02-13 10:18 UTC, JTaeuber commented on website/content/docs/0 - downscaler/5 - Layers.mdx
> +Layers are layers of [values](ref:docs-values).
I am not the biggest fan of this explanation of layers. 😅
Maybe something along the lines of:

"Layers are a concept defining which values to use above others."

2025-02-13 10:18 UTC, JTaeuber commented on website/content/docs/0 - downscaler/5 - Layers.mdx
> +## Environment
I know this is on the layer site but maybe we should still write Workload Layer, Namespace Layer, etc into the headings

2025-02-13 10:18 UTC, JTaeuber commented on website/content/docs/0 - downscaler/5 - Layers.mdx
> +The most specific layer, if a value gets set here it will be used for scaling.
```suggestion
The most specific layer. If a value gets set here it will be used for scaling.
```

2025-02-13 10:18 UTC, JTaeuber commented on website/content/docs/0 - downscaler/6 - types/1 - Duration.mdx
> +A duration can be represented as an [integer, in which case it represents seconds](#integer-seconds) or a [duration string](#duration string).
duration string is a dead link

2025-02-13 14:56 UTC, JTaeuber requested changes

2025-02-13 14:56 UTC, JTaeuber commented on website/content/guides/1 - developing/3 - Maintaining the Repository.mdx
> +This will intern retrigger [the workflow](ref:docs-workflows#check-for-release) run which then automatically removes the <GithubLabel label="needs approval"/> label and allows for the pull request to
```suggestion
This will in turn retrigger [the workflow](ref:docs-workflows#check-for-release) run which then automatically removes the <GithubLabel label="needs approval"/> label and allows the pull request to be merged.
```

2025-02-13 14:56 UTC, JTaeuber commented on website/static/manifest.json
Still uses the caas logo svg everywhere.

2025-02-14 05:54 UTC, jonathan-mayer commented on website/content/docs/0 - downscaler/7 - Workload Types.mdx
> +Scales by setting the node selector to match none of the nodes, which stops pods running on any node.
idk, that would imply they would just not be created, but already running ones are stopped too

2025-02-14 05:57 UTC, jonathan-mayer commented on website/content/docs/1 - Workflows.mdx
> +- Runs on: push, pull_request.opened, pull_request.synchronize, pull_request.reopened
but it does also run on any push, even without an open pull request
https://github.com/caas-team/GoKubeDownscaler/blob/main/.github/workflows/pre_commit.yaml#L4

2025-02-18 13:12 UTC, jonathan-mayer commented
did some things. got some more todos which along with the left over threads i still have to do before we can think about merging this:
- [ ] Fix navbar for too small  screens (swizzle to use a small logo when small)
- [ ] try to fix the search bar search icon to switch to white in dark mode (optional)
- [ ] align all small screen views to be the same, dont use both md: and lg:

2025-02-19 10:50 UTC, JTaeuber requested changes

2025-02-19 10:50 UTC, JTaeuber commented on website/plugins/disable-styling.cts
> +// this will add an "useTailwind" css class which disables all css classes
```suggestion
// this will add a "useTailwind" css class which disables all css classes
```

2025-02-19 10:50 UTC, JTaeuber commented on website/plugins/disable-styling.cts
> +// this is to be able to disable infimas/docusauruses globally applied element selectors
```suggestion
// this is needed to disable infimas/docusauruses globally applied element selectors
```

2025-02-19 11:50 UTC, jonathan-mayer commented
Found more issues:
- [ ] lists dont show dot
- [ ] the home breadcrumb in docs is higher than the rest
- [ ] probs more

2025-02-21 07:51 UTC, jonathan-mayer commented
The formatting using tailwind seems to be a bit broken still, i will try to fix it asap

2025-02-24 08:56 UTC, JTaeuber approved these changes
👍🏻

2025-02-24 08:59 UTC, merged