Feat/retries on conflict error
caas-team/GoKubeDownscaler pull request #74
Opened 2024-12-14 17:30 UTC by samuel-esp

## Motivation

Give the user the possibility to choose how to handle HTTP 409 conflict errors. Such conflicts typically occur when another entity (such as an HPA, CI/CD pipeline, or manual intervention) modifies a resource just before KubeDownscaler processes it

See #68 or https://github.com/caas-team/py-kube-downscaler/issues/111

## Changes

- Introduced `--max-retries-on-conflict` argument like in Py-Kube-Downscaler
- Introduced GetWorkload() function to handle the use case when the downscaler needs to retrieve a single Kubernetes resource (before it was only possible to get a list of resources, i.e `kubectl get deploy -n default`). the old GetWorkload() was renamed to GetWorkloads() to reflect the changes
- Introduced a new function GetResourceType() that returns the resource type (string)
- Refactored the main loop to be able to use `--max-retries-on-conflict`

## Tests done

- Unit Tests

## TODO

- [x] I've assigned myself to this PR
- [ ] Refactored docs
- [ ] Added more unit tests on this specific use case

2025-01-07 09:44 UTC, jonathan-mayer reviewed
Also just so you know, the workflows were broken for forks (thats why they were failing). We've fixed it but it will now run every workflow twice in this and the other pr. If you want you can rebase the branches with main and the errors will go away.

2025-01-07 12:31 UTC, jonathan-mayer commented on internal/pkg/scalable/cronjobs.go
> +}
I really think we shouldn't have a whole other function just to get just 1 of the resource.

```suggestion
// getCronJobs is the getResourceFunc for CronJobs
func getCronJobs(name, namespace string, clientsets *Clientsets, ctx context.Context) ([]Workload, error) {
    var results []Workload
    if name != "" {
        cronjob, err := clientsets.Kubernetes.BatchV1().CronJobs(namespace).Get(ctx, name, metav1.GetOptions{})
        if err != nil {
            return result, fmt.Errorf("failed to get cronjob: %w", err)
        }
        results = append(results, &suspendScaledWorkload{&cronJob{cronjob}})
        return results
    }

    cronjobs, err := clientsets.Kubernetes.BatchV1().CronJobs(namespace).List(ctx, metav1.ListOptions{TimeoutSeconds: &timeout})
    if err != nil {
        return nil, fmt.Errorf("failed to get cronjobs: %w", err)
    }
    for _, item := range cronjobs.Items {
        results = append(results, &suspendScaledWorkload{&cronJob{&item}})
    }
    return results, nil
}
```

I think we should keep the client.GetWorkload and GetWorkloads in single functions. This will also help abstract this configuration away.

2025-02-19 20:52 UTC, samuel-esp commented on cmd/kubedownscaler/main.go
> +						if strings.Contains(err.Error(), "the object has been modified") {
That's elegant jonathan, will refactor to this. Great find!

2025-02-19 23:34 UTC, samuel-esp commented
@jonathan-mayer rebased and included the previous suggestions. Just a couple of things to note:

1. Pre-Commit failed because the specific `getResourceFunc` for each resource has duplicate code" detected (which is true because the logic is shared across them). So, eventually, we should try to think about a strategy to tackle that
2. Pre-Commit also suggested to lower a bit `startScanning` complexity. What would you refactor inside that?

2025-02-20 06:16 UTC, jonathan-mayer commented
Ill have a look over it. 

> 1. Pre-Commit failed because the specific getResourceFunc for each resource has duplicate code" detected (which is true because the logic is shared across them). So, eventually, we should try to think about a strategy to tackle that

I do get that it detects it as duplicate, but im not entirely sure how to avoid it. I think in theory it is avoidable by just having list and get in separate functions. Another way would also be to refactor to use the dynamic client again, although i would still like to avoid that.

> 2. Pre-Commit also suggested to lower a bit startScanning complexity. What would you refactor inside that?

I think we could refactor the function called in the go routine out.

2025-02-20 18:43 UTC, samuel-esp commented
1. I perfectly agree with you, I don't see anything wrong with having them duplicate. I will go nolint on them
2. I'll extract the go routine from the function

2025-02-20 19:56 UTC, samuel-esp commented
@jonathan-mayer I refactored the go func out of the `startScanning` function however I'm not sure what could be the best name for the that

2025-02-21 05:58 UTC, jonathan-mayer commented
> @jonathan-mayer I refactored the go func out of the `startScanning` function however I'm not sure what could be the best name for the that. `attemptScan` was the best I came up with

i think the current function name should be good for now. Although i would not put a anonymous function in the attemptScan function, but instead just run the attemptScan function in a goroutine so `go attemptScan()`. Also just a heads up, it might take some time until i get around to review this.

2025-02-21 07:23 UTC, samuel-esp commented
Don't worry Jonathan, absolutely no rush take your time

2025-02-25 06:56 UTC, jonathan-mayer commented
I think we should change up the GetResource funcs again. They should only handle listing and then every scalableResouce should have a re-get function which regets itself from kubernetes. it could like something like this:

```
func (c *cronJob) Reget(clientsets *Clientsets, ctx context.Context) {
	*c, err = clientsets.Kubernetes.BatchV1().CronJobs(c.Namespace).Get(c.Name, ctx,, metav1.GetOptions{})
	if err != nil {
		// TODO handle error
	}
}
```

2025-02-25 07:05 UTC, jonathan-mayer requested changes

2025-02-25 19:35 UTC, samuel-esp commented on internal/pkg/util/config.go
> +		"max-retries-on-error",
nice catch!

2025-02-25 21:15 UTC, samuel-esp commented
> I think we should change up the GetResource funcs again. They should only handle listing and then every scalableResouce should have a re-get function which regets itself from kubernetes. it could like something like this:
> 
> ```go
> func (c *cronJob) Reget(clientsets *Clientsets, ctx context.Context) {
> 	*c, err = clientsets.Kubernetes.BatchV1().CronJobs(c.Namespace).Get(c.Name, ctx,, metav1.GetOptions{})
> 	if err != nil {
> 		// TODO handle error
> 	}
> }
> ```

Implemented, the linter still complain about 2 things:
- deployment/statefulset class duplication
- RegetWorkload and its specific methods returns an interface type

I mean the first one could be true, the second one it seems legit to return an interface type in that case

2025-02-26 10:59 UTC, jonathan-mayer requested changes
looked at main and clientgo

2025-02-26 11:06 UTC, samuel-esp commented on internal/api/kubernetes/client.go
> +func (c client) RegetWorkload(name, namespace, resourceType string, ctx context.Context) (scalable.Workload, error) {
fine, I'll refactor this

2025-02-26 21:03 UTC, samuel-esp commented
refactored the way you suggested, still having "duplicate" suggestion on linting. I think we can't do much about that

2025-02-28 06:19 UTC, jonathan-mayer requested changes

2025-02-28 06:19 UTC, jonathan-mayer commented on cmd/kubedownscaler/main.go
> +	}
im not too much of a fan of putting logs in if statements and this message wouldn't fit into the case where `once` is specified (the main proposed use case of the retries argument). so i would try to change up these messages so that it is a bit more generic. 

`slog.Error(failed to scan workload, "tries/attempts", config.MaxRetriesOnConflict+1, ...)`

\*i would choose "tries" or "attempts", not both


we should be able to put this after the for loop. then instead of having the `scanSucceeded` bool we can just return where the `scanSucceeded = true` is now

2025-02-28 06:19 UTC, jonathan-mayer commented on internal/pkg/scalable/cronjobs.go
> +	return nil
```suggestion
    var err error
	c.CronJob, err = clientsets.Kubernetes.BatchV1().CronJobs(c.Namespace).Get(ctx, c.Name, metav1.GetOptions{})
	if err != nil {
		return fmt.Errorf("failed to get cronjob: %w", err)
	}

	return nil
```

this should be done with every resource

2025-02-28 06:19 UTC, jonathan-mayer commented on internal/pkg/scalable/workload.go
> +	Reget(clientsets *Clientsets, ctx context.Context) error
i think this should be in the scalableResource interface

2025-02-28 11:31 UTC, samuel-esp commented on cmd/kubedownscaler/main.go
> +				slog.Error("failed to scan workload", "error", err, "workload", workload.GetName(), "namespace", workload.GetNamespace())
I got your point, I refactored that accordingly

2025-03-03 06:21 UTC, jonathan-mayer requested changes

2025-03-03 06:21 UTC, jonathan-mayer commented on cmd/kubedownscaler/main.go
> +			}()
oh, can you actually redo what you did [here](https://github.com/caas-team/GoKubeDownscaler/pull/74#discussion_r1905199891)

2025-03-03 06:21 UTC, jonathan-mayer commented on cmd/kubedownscaler/main.go
>  				}
from https://github.com/caas-team/GoKubeDownscaler/pull/74#discussion_r1969015079
> or we could wrap calling the attemptScan function in a anonymous func which handles waitGroup.Done and error handling

2025-03-03 17:35 UTC, samuel-esp commented on cmd/kubedownscaler/main.go
> +			}()
yes!

2025-03-04 07:03 UTC, jonathan-mayer submitted a review, later dismissed
I think this should be good to go

2025-03-04 17:30 UTC, samuel-esp commented
Done

2025-03-05 10:49 UTC, jonathan-mayer approved these changes

2025-03-07 16:16 UTC, samuel-esp commented
@jonathan-mayer rebased and cleaned history

2025-03-10 13:23 UTC, jonathan-mayer requested changes

2025-03-10 13:23 UTC, jonathan-mayer commented on internal/pkg/scalable/scaledobjects.go
> +// getScaledObjects is the getResourceFunc for Keda ScaledObjects. //nolint:dupl.
do we still need this no lint here if we have the whole file nolinted fo rthis linter

```suggestion
// getScaledObjects is the getResourceFunc for Keda ScaledObjects.
```

2025-03-10 13:23 UTC, jonathan-mayer commented on internal/pkg/scalable/stacks.go
> +//nolint:dupl // necessary to handle different workload types separately
```suggestion
// getStacks is the getResourceFunc for Zalando Stacks.
//nolint:dupl // necessary to handle different workload types separately
```

2025-03-11 11:42 UTC, jonathan-mayer commented on internal/pkg/scalable/stacks.go
> +//nolint:dupl // necessary to handle different workload types separately
oh acutally, can you remove the //nolint:dupl on that func entirely. the file already has the nolint for this

2025-03-11 14:42 UTC, samuel-esp commented on internal/pkg/scalable/stacks.go
> +//nolint:dupl // necessary to handle different workload types separately
done!

2025-03-11 14:43 UTC, samuel-esp commented
I think everthing is ready now

2025-03-12 06:42 UTC, jonathan-mayer submitted a review, later dismissed

2025-03-12 07:07 UTC, jonathan-mayer commented
Resolved merge conflicts. Feel free to merge whenever

2025-03-12 09:46 UTC, merged