Feat/leader election mechanism using leases
caas-team/GoKubeDownscaler pull request #75
Opened 2024-12-18 12:38 UTC by samuel-esp

## Motivation

In order to avoid conflicts among multiple replicas when modifying resources (see #68) it is necessary to implement a leader election mechanism that elects a leader among the available replicas. The feature should be implemented using Leases (see [Kubernetes Leases Explained](https://kubernetes.io/docs/concepts/architecture/leases/))

## Changes

- Introduced a new atomic variable inside `main.go` that stores the state of the replica (`isLeader`)  
- Introduced a nested GoRoutine that manages lease lifecycle, the GoRoutine periodically checks the lease status and creates/renews the lease. When a termination signal is sent by the user or by another entity and the replica is currently the leader, it handles a graceful termination by deleting the current lease  
- Implemented 2 new functions in `client.go` to manage lease lifecycle used by the nested GoRoutine mentioned above (`CreateOrUpdateLease` and `DeleteLease`). The first function calls the function `GetCurrentNamespaceFromFile` from `util.go` (which reads the ServiceAccount used by the downscaler) to understand the namespace where it needs to create the lease object  
- Added a new `Role` and `RoleBinding` to the Helm chart that allows the downscaler to create, get, update and delete `Leases` inside its own namespace  

## Tests done

- Live Tests

## TODO

- [ ] Unit Testing
- [ ] Further Live Testing

2025-01-07 08:26 UTC, jonathan-mayer commented on internal/api/kubernetes/client.go
> +// CreateOrUpdateLease attempts to acquire and maintain a lease for leadership.
The kubernetes package/client should only have very basic functions which can in most cases basically be linked to a single api request to the cluster. So I would make a leader package for all the logic and only have a function here to create/update a lease object.

2025-01-07 08:48 UTC, jonathan-mayer requested changes
Had a first look at the changes. What I've found is that there is actually a leader election package from k8s. I think we should use that one since it makes leader election easier and less verbose. 
https://pkg.go.dev/k8s.io/client-go/tools/leaderelection

I've also found this articel which gives an example of how to use it https://dev.to/sklarsa/how-to-add-kubernetes-powered-leader-election-to-your-go-apps-57jh

2025-01-25 16:47 UTC, samuel-esp commented on deployments/chart/templates/_helpers.tpl
> +    - delete
Done!

2025-01-25 16:47 UTC, samuel-esp commented on internal/api/kubernetes/client.go
> +// CreateOrUpdateLease attempts to acquire and maintain a lease for leadership.
refactored using the "https://pkg.go.dev/k8s.io/client-go/tools/leaderelection" package

2025-01-25 16:58 UTC, samuel-esp commented
> Had a first look at the changes. What I've found is that there is actually a leader election package from k8s. I think we should use that one since it makes leader election easier and less verbose. https://pkg.go.dev/k8s.io/client-go/tools/leaderelection
> 
> I've also found this articel which gives an example of how to use it https://dev.to/sklarsa/how-to-add-kubernetes-powered-leader-election-to-your-go-apps-57jh

I've refactored the PR to use the native "leader-election" package, unit tests are ok, live testing as well but to be sure I would prefer a live testing from another person as well

Also, there is still something to improve in the code structure I think, so I'm waiting for the review

Finally, we should discuss about the "lease-role", I think it will be easier with a separate role

2025-01-25 17:08 UTC, samuel-esp commented on deployments/chart/templates/_helpers.tpl
> +{{- end -}}
@jonathan-mayer I'll leave this discussion open here

2025-01-25 23:17 UTC, jonathan-mayer commented
Resolved the left over merge conflicts (which were basically already solved, no idea why GitHub showed them. Either way ima have a look over this in the next days. Thanks @samuel-esp!

2025-01-26 00:39 UTC, jonathan-mayer requested changes
Great work @samuel-esp. One big thing we have to watch out for though is that I think its really important to be able to easily test the downscaler locally, this is currently no longer possible because it wants to get the namespace of the current pod. 

I think what we should do is put the GetNamespace func call directly above the client.CreateLease call. If the GetNamespace func returns empty, log info that it seems not to be running on cluster and it will run without leader election. Additionally put an guard clause above the client.CreateLease call and just run the program directly:
```go
downscalerNamespace, err := kubernetes.GetCurrentNamespaceFromFile()
if err != nil {
  slog.Info("running outside of cluster; skipping leader election", "error", err)
  startScanning()
  return
}

lease, err := client.CreateLease(leaseName, downscalerNamespace)
if err != nil {
  slog.Error("failed to create lease", "error", err)
  os.Exit(1)
}

// ...
```

2025-01-26 00:39 UTC, jonathan-mayer commented on cmd/kubedownscaler/main.go
> +				run(ctx)
i dont see why we cant just call the loop function directly here

2025-01-26 00:39 UTC, jonathan-mayer commented on cmd/kubedownscaler/main.go
> +func loop(client kubernetes.Client, ctx context.Context, layerCli, layerEnv *values.Layer, config *util.RuntimeConfiguration) {
would rename to `startScanning` or similar

2025-01-26 00:39 UTC, jonathan-mayer commented on cmd/kubedownscaler/main.go
> +		ReleaseOnCancel: true,
> If you set this to true, you must ensure all code guarded by this lease has successfully completed prior to cancelling the context, or you may have two processes simultaneously acting on the critical path.

could this cause problems when a sigterm comes in and a scan is underway? or do all the api calls just get canceled via the context before this can cause issues?

2025-01-26 00:39 UTC, jonathan-mayer commented on deployments/chart/templates/_helpers.tpl
> +*/}}
```suggestion
```

2025-01-26 00:42 UTC, jonathan-mayer commented on deployments/chart/templates/_helpers.tpl
> +{{- end -}}
@JTaeuber

2025-01-26 15:37 UTC, samuel-esp commented
> Great work @samuel-esp. One big thing we have to watch out for though is that I think its really important to be able to easily test the downscaler locally, this is currently no longer possible because it wants to get the namespace of the current pod.
> 
> I think what we should do is put the GetNamespace func call directly above the client.CreateLease call. If the GetNamespace func returns empty, log info that it seems not to be running on cluster and it will run without leader election. Additionally put an guard clause above the client.CreateLease call and just run the program directly:
> 
> ```go
> downscalerNamespace, err := kubernetes.GetCurrentNamespaceFromFile()
> if err != nil {
>   slog.Info("running outside of cluster; skipping leader election", "error", err)
>   startScanning()
>   return
> }
> 
> lease, err := client.CreateLease(leaseName, downscalerNamespace)
> if err != nil {
>   slog.Error("failed to create lease", "error", err)
>   os.Exit(1)
> }
> 
> // ...
> ```

@jonathan-mayer thanks a lot for quickly reviewing the PR. I've improved this behavior you mentioned and now if the leader election couldn't be completed the main process won't stop. I added a couple of logs messages to make the user aware of the potential conflicts this situation could lead to 

I refactored the code according to the suggestions, I left a couple of discussions open (for the dedicated lease `Role`, and for the `ReleaseOnCancel` behavior)

2025-01-26 18:41 UTC, jonathan-mayer requested changes
Thanks for resolving the threads so fast, I have to test this still, but i think the code looks good and I dont see why it wouldn't work. We should maybe still discuss the left open threads before merging real quick.

2025-01-26 18:41 UTC, jonathan-mayer commented on cmd/kubedownscaler/main.go
> +	}
CreateLease only returns an error when os.Hostname does. We shouldn't continue at all if we seem to be running in cluster but something as simple as the hostname fails.
The Warning about proceeding without leader election should be placed in the guard clause above, and we should just log the error and exit here.

2025-01-26 19:00 UTC, jonathan-mayer commented on cmd/kubedownscaler/main.go
> +		ReleaseOnCancel: true,
I will still have to test this either way, but ive looked a bit into this. This should not cause any problems, since all api calls should instantly cancel once the context is. If in the future we see any problems arising from this we can simply set this to false. This would cause the RunOrDie function call to stop blocking when the context is canceled which in turn returns the main, forcibly terminating all other goroutines. After that the lease would expire after the LeasePeriod, giving the program even more time to finish up. Only reason I am against doing this right now is that it does mean that there will be more downtime and it really shouldn't cause any problems like it is right now.

2025-01-26 19:10 UTC, jonathan-mayer commented on deployments/chart/templates/_helpers.tpl
> +{{- end -}}
I'll still wait to hear something back from @JTaeuber before resolving this, but I also just realised that not having this separate would have dire consequences in a non-cluster-wide installation where the downscalers own namespace is not selected to be scaled. I currently can't come up with any solutions which would have any benefit over just having this separate.

2025-01-26 19:48 UTC, jonathan-mayer requested changes
Turns out I did have a bit more to say about this 🙃

2025-01-26 19:48 UTC, jonathan-mayer commented on cmd/kubedownscaler/main.go
> +		RetryPeriod:     5 * time.Second,
Also, on the topic of the TODO for fine tuning these values. 
I think it would be smart to something more like this:
```suggestion
		LeaseDuration:   30 * time.Second,
		RenewDeadline:   20 * time.Second,
		RetryPeriod:     5 * time.Second,
```
Its common to have the RenewDeadline be 2/3 of the LeaseDuration. I think the RetryPeriod being 5s is fine, since its not like the downscaler needs to be super high availability and we already send a lot of api requests as it is. I think the Lease Duration being 30s is a good middle ground for the downscaler, it means that the leader still has 3-4 chances at renewing and also 30s being the default Scan interval this means that at least when using the default interval there is basically 0 downtime between scans. I would go against retrieving these values from the specified scan interval, because if these values are too low it will cause a lot more leader switches and in turn unnecessary overhead.

2025-01-26 19:48 UTC, jonathan-mayer commented on cmd/kubedownscaler/main.go
>  	}
Instead of exiting here, we should return an error and handle it in main. 

If the func was called from within the LeaderElection we can then cancel the context and not exit, which releases the lease instead of having to wait for the lease to expire.

In the case where we run without leader election, we can simply print the error, cancel the context and exit. No if err check or letting the context stop the program required.

2025-01-27 20:06 UTC, samuel-esp commented on cmd/kubedownscaler/main.go
> +	}
```go
lease, err := client.CreateLease(leaseName, downscalerNamespace)
if err != nil {
slog.Warn("failed to create lease", "error", err)
os.Exit(1)
}

defer cancel()
```
@jonathan-mayer to resolve this and exit from the process when the hostname retrieval fails, I had to move the `defer cancel()` below since the linter won't allow me to commit for  `exitAfterDefer: os.Exit will exit, and `defer cancel()` will not run (gocritic)`

2025-01-27 20:39 UTC, jonathan-mayer commented on cmd/kubedownscaler/main.go
> +	}
i think i wouldn't move the defer cancel, im not sure if the linter picks up on it, if not we could do a nolint for the os.Exit but i think we should just be able to cancel the context before the exit.

```go
lease, err := client.CreateLease(leaseName, downscalerNamespace)
if err != nil {
slog.Warn("failed to create lease", "error", err)
cancel()
os.Exit(1)
}
```

2025-01-27 20:42 UTC, samuel-esp commented on cmd/kubedownscaler/main.go
>  	}
refactored

2025-01-27 20:44 UTC, samuel-esp commented
@jonathan-mayer I left another discussion open for a linter suggestion that may go against one of the suggestion you said before about initializing context

2025-01-27 20:45 UTC, samuel-esp commented on cmd/kubedownscaler/main.go
> +	}
I left this open since it could conflict with what you said there

> @[jonathan-mayer](https://github.com/jonathan-mayer) jonathan-mayer [Jan 26, 2025](https://github.com/caas-team/GoKubeDownscaler/pull/75#discussion_r1929628831)
> 
> put this directly after initializing the context

2025-01-29 08:18 UTC, JTaeuber commented on deployments/chart/templates/_helpers.tpl
> +{{- end -}}
Yeah we should keep this seperate for now so we don't allow unnecessary actions.

2025-01-29 09:05 UTC, jonathan-mayer commented on cmd/kubedownscaler/main.go
> +				startScanning(client, ctx, &layerCli, &layerEnv, config)
we should handle the error here. and cancel the context if err != nil

2025-01-29 09:05 UTC, jonathan-mayer commented on cmd/kubedownscaler/main.go
> +				slog.Info("stopped leading")
Im debating if we should implement this to actually stop the loop. Im guessing it would rely on this instantly stopping the application before further action. how it is right now, it would do nothing on stop and let run or die do its thing until it stops blocking and the main thread returns

2025-01-29 09:05 UTC, jonathan-mayer commented on cmd/kubedownscaler/main.go
>  	}
did you push the changes for this yet?

2025-01-29 09:38 UTC, jonathan-mayer commented on cmd/kubedownscaler/main.go
>  	}
Did you push the changes yet?

2025-01-29 17:31 UTC, samuel-esp commented on cmd/kubedownscaler/main.go
>  	}
sorry, I lost some part of the commit. Happens sometimes after running precommit, the memory/file system of my ide gets corrupted

2025-01-29 17:50 UTC, samuel-esp commented on cmd/kubedownscaler/main.go
> +				slog.Info("stopped leading")
you mean like exiting from the application?

2025-01-30 07:33 UTC, jonathan-mayer commented on cmd/kubedownscaler/main.go
> +				slog.Info("stopped leading")
yea, basically

2025-01-30 07:36 UTC, jonathan-mayer commented on cmd/kubedownscaler/main.go
> +		return err
I wouldn't print the error here, instead return a fmt.Errorf formatted error

2025-01-31 06:45 UTC, jonathan-mayer requested changes

2025-01-31 06:45 UTC, jonathan-mayer commented on cmd/kubedownscaler/main.go
> +				os.Exit(1)
I thought more of a soft stop. like instead of doing while true implement while running (with context maybe) to stop the loop and cancel the context to stop the active api requests

2025-01-31 06:45 UTC, jonathan-mayer commented on cmd/kubedownscaler/main.go
>  		)
would remove this slog.error

2025-01-31 16:24 UTC, samuel-esp commented on cmd/kubedownscaler/main.go
> +				os.Exit(1)
@jonathan-mayer could you check the new commit, I don't know if i understood you well. I don't know if you wanted me to create a new function just to stop the context. What I did was just to put the cancel() instead of the os.Exit(1)

2025-02-03 06:37 UTC, jonathan-mayer commented
> @jonathan-mayer before merging: what do you think about implemeting a custom argument to skip leader election if needed? like `--skip-leader-election`.
> 
> for example the [VPA](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/docs/faq.md#can-i-run-the-vpa-in-an-ha-configuration) lets the user choose if enabling the leader election or not

sure, lets then also update the helm chart to auto set it if replicas is >1 and make an additional value in the values.yaml to disable it

2025-02-03 08:43 UTC, jonathan-mayer requested changes

2025-02-03 08:43 UTC, jonathan-mayer commented on cmd/kubedownscaler/main.go
> +				os.Exit(1)
ive looked into this a bit more and this should be fine

2025-02-04 20:49 UTC, samuel-esp commented on cmd/kubedownscaler/main.go
> +		return
@jonathan-mayer refactored, I saw the pipeline returned me a lint suggestion

cmd/kubedownscaler/main.go:34:1: calculated cyclomatic complexity for function main is 11, max is 10 (cyclop)

So I refactored the functions as showed in the last commit

2025-02-05 10:54 UTC, jonathan-mayer requested changes

2025-02-05 10:54 UTC, jonathan-mayer commented on cmd/kubedownscaler/main.go
> -	err := layerEnv.GetLayerFromEnv()
i dont think these should be in functions in main, either we keep this all in the main func or we have to put these/refactor other functions in the packages responsible for handling these

2025-02-05 10:54 UTC, jonathan-mayer commented on cmd/kubedownscaler/main.go
> +	}
shouldnt it then actually skip leaderelection here, how it is right now unless leader election is also disabled it will just error because the namespace is "".

What we could also do is make leader election disabled by default, only enabled via the argument. Put this getting the namespace after the check if leader election is disabled and error and exit when the namespace couldn't be gotten.

2025-02-05 10:54 UTC, jonathan-mayer commented on internal/pkg/util/config.go
> +	LeaderElectionEnabled bool
```suggestion
	// LeaderElection sets if leader election should be performed.
	LeaderElection bool
```

2025-02-05 10:54 UTC, jonathan-mayer commented on internal/pkg/util/config.go
> +	)
```suggestion
	flag.BoolVar(
		&c.Once,
		"leader-election",
		false,
		"enables leader election (default: false)",
	)
```

2025-02-05 10:54 UTC, jonathan-mayer commented on deployments/chart/templates/leaserole.yaml
put a if around all this to only make the role when leader election is enabled. for this i would add a leader election enabled field in the helpers and use it here and in the deployment.yaml where you add the cli argument to enable leader election

2025-02-07 09:09 UTC, jonathan-mayer requested changes

2025-02-07 09:09 UTC, jonathan-mayer commented on cmd/kubedownscaler/main.go
> +		runWithoutLeaderElection(client, ctx, &layerCli, &layerEnv, config)
```suggestion
		slog.Error("failed to get namespace or running outside of cluster; disable leader election to continue", "error", err)
		os.Exit(1)
```

2025-02-07 14:25 UTC, samuel-esp commented
Refactored the helm chart, left open one discussion above

2025-02-10 07:29 UTC, jonathan-mayer commented on deployments/chart/templates/_helpers.tpl
> +If replicaCount > leader election is enabled by default.
```suggestion
If replicaCount is greater than 1 leader election is enabled by default.
```

2025-02-10 07:30 UTC, jonathan-mayer commented on deployments/chart/values.yaml
> +# If replicaCount is greater than 1, the leader election is enabled by default
```suggestion
# If replicaCount is greater than 1, the leader election is enabled by default
replicaCount: 1
```

2025-02-10 08:48 UTC, jonathan-mayer commented on cmd/kubedownscaler/main.go
> +		runWithoutLeaderElection(client, ctx, &layerCli, &layerEnv, config)
Just to reiterate from my previous comment on this. I think it would be good to if someone explicitly enables leader election via the cli argument, we should enforce that wish. This could otherwise easily lead to unwanted behavior from wrong configuration. One of the main improvements of the gokubedownscaler is that unclear/wrong configuration will throw an error to show the user their fault, instead of just ignoring it and doing unexpected things.

2025-02-11 06:32 UTC, jonathan-mayer requested changes
Ok, im pretty sure we can merge after this

2025-02-11 06:32 UTC, jonathan-mayer commented on cmd/kubedownscaler/main.go
> +	}
we can put this into the client.CreateLease function and with that make the func private

2025-02-11 06:32 UTC, jonathan-mayer commented on cmd/kubedownscaler/main.go
> +		slog.Warn("failed to create lease", "error", err)
```suggestion
		slog.Error("failed to create lease", "error", err)
```

2025-02-11 06:32 UTC, jonathan-mayer commented on cmd/kubedownscaler/main.go
> +		slog.Warn("couldn't get namespace or running outside of cluster; skipping leader election", "error", err)
```suggestion
		slog.Error("couldn't get namespace or running outside of cluster", "error", err)
```

2025-02-11 06:32 UTC, jonathan-mayer commented on cmd/kubedownscaler/main.go
> +	slog.Warn("proceeding without leader election, this may cause multiple downscaler instances to conflict when modifying the same resources")
```suggestion
	slog.Warn("proceeding without leader election; this could cause errors when running with multiple replicas")
```

2025-02-11 06:32 UTC, jonathan-mayer commented on cmd/kubedownscaler/main.go
>  	client kubernetes.Client,
could we actually combine the start Scanning and scanWorkloads function, it only adds 1 log line and removes a bit of error handling boiler plate

2025-02-11 06:32 UTC, jonathan-mayer commented on deployments/chart/templates/leaserole.yaml
> +{{- if include "go-kube-downscaler.leaderElection" . }}
```suggestion
{{- if include "go-kube-downscaler.leaderElection" . -}}
```

2025-02-11 06:32 UTC, jonathan-mayer commented on deployments/chart/values.yaml
> +# If replicaCount is greater than 1, the leader election is enabled by default
```suggestion
# If replicaCount is greater than 1, leader election is enabled by default
```

2025-02-11 14:02 UTC, jonathan-mayer requested changes

2025-02-11 14:02 UTC, jonathan-mayer commented on internal/api/kubernetes/client.go
> +	}
return error here

2025-02-12 05:54 UTC, jonathan-mayer commented on internal/api/kubernetes/client.go
> +	}
```suggestion
	leaseNamespace, err := getCurrentNamespace()
	if err != nil {
		return nil, fmt.Errorf("failed to get namespace or running outside of cluster: %w", err)
	}
```

2025-02-13 07:14 UTC, jonathan-mayer requested changes

2025-02-13 07:14 UTC, jonathan-mayer commented on cmd/kubedownscaler/main.go
> +
please put this directly after initializing the context

2025-02-13 07:14 UTC, jonathan-mayer commented on internal/api/kubernetes/client.go
> +		slog.Error("failed to get hostname", "error", err)
```suggestion
```

2025-02-13 08:35 UTC, jonathan-mayer approved these changes

2025-02-19 08:08 UTC, jonathan-mayer commented
i totally forgot to merge this

2025-02-19 08:08 UTC, merged